import assert from 'node:assert/strict';
import {activityRow,shiftWindow,visibleActivityEmployee} from '../lib/activity.ts';
import {mayCallEndpoint} from '../lib/permissions.ts';
import {syncActivity} from '../lib/activity-sync.ts';
import {readActivity} from '../lib/activity-store.ts';
import {openDatabase} from '../server/sqlite.ts';
const now=Date.parse('2026-10-01T07:00:00Z'),at=new Date(now).toISOString(),e={id:'e',name:'Operator',login:'op',role:'operator',department:'1'},head={...e,id:'head',role:'department_head'},schedule={days:[1,2,3,4,5],start:'08:00',end:'17:00',breakMinutes:60};
const sample={employeeId:'e',skId:1,locked:false,calls:1,lastCallAt:'2026-10-01T05:00:00Z',lastCallEnd:'2026-10-01T05:01:00Z',callSeconds:60,observedAt:at,status:'normal',statusAt:'2026-10-01T05:01:00Z',breakSeconds:0,breakObservedSince:at,lastBusyAt:'',breakEndedAt:'',day:'2026-10-01'};
const row=(s=sample,t=now)=>activityRow(e,schedule,s,{at:'',count:0},t);
assert.equal(row().state,'idle');
assert.equal(row({...sample,status:'speaking'}).state,'active');
assert.equal(row({...sample,status:'away',breakSeconds:3599}).state,'break');
assert.equal(row({...sample,status:'away',breakSeconds:3601}).state,'idle');
assert.equal(row({...sample,status:'unknown'}).state,'unknown');
assert.equal(row({...sample,observedAt:'2026-10-01T06:50:00Z'}).state,'unknown');
assert.equal(row({...sample,locked:true}).state,'unknown');
assert.equal(row(sample,Date.parse('2026-10-01T14:00:00Z')).state,'off');
assert.equal(row(sample,Date.parse('2026-10-03T07:00:00Z')).state,'off');
assert.equal(activityRow(e,schedule,sample,{at:'2026-10-01T06:59:00Z',count:1},now).state,'active');
assert.equal(visibleActivityEmployee(head,{...e,department:'2'}),false);
assert.equal(visibleActivityEmployee(head,e),true);
assert.equal(mayCallEndpoint(e,new URL('https://crm/api/activity'),'GET',{}),false);
assert.equal(mayCallEndpoint(head,new URL('https://crm/api/activity'),'GET',{}),true);
assert.equal(mayCallEndpoint(head,new URL('https://crm/api/activity'),'POST',{}),false);
assert.equal(shiftWindow(schedule,now).start,Date.parse('2026-10-01T05:00:00Z'));
const d=openDatabase(':memory:');
for(const sql of ['CREATE TABLE settings(id TEXT PRIMARY KEY,data TEXT)','CREATE TABLE employees(id TEXT PRIMARY KEY,data TEXT)','CREATE TABLE events(id TEXT PRIMARY KEY,at TEXT,data TEXT)'])await d.prepare(sql).run();
await d.prepare('INSERT INTO employees VALUES(?,?)').bind(e.id,JSON.stringify(e)).run();
for(const [id,v] of Object.entries({'skorozvon':{login:'x',apiKey:'x',clientId:'x',clientSecret:'x'},'activity-sk-map':{e:1},'activity-provider-bootstrap':{url:'https://shard5-lb2.skorozvon.ru/bootstrap'},'activity-schedules':{'1':schedule}}))await d.prepare('INSERT INTO settings VALUES(?,?)').bind(id,JSON.stringify(v)).run();
let callsRequested=0;
const request=async(url,options)=>{
 const path=new URL(url).pathname;let data;
 if(path==='/oauth/token')data={access_token:'test'};
 else if(path==='/api/v2/users')data=[{id:1,uuid:'uuid',locked:false}];
 else if(path==='/api/reports/calls_total.json'){callsRequested++;const body=JSON.parse(options.body);data={data:[{id:body.page,user:{id:1},started_at:body.page===1?'2026-10-01 05:01:00':'2026-10-01 05:00:00',duration:30}],total_pages:2};}
 else if(path==='/api/v2/calls/1')data={user_id:1,ended_at:'2026-10-01T05:01:30Z'};
 else if(path==='/bootstrap')data={phone_bus_uri:'https://pod1-ncc13-lb1.skorozvon.ru'};
 else if(path==='/postman/user_states')data=[{user_id:'uuid',status:'normal',status_changed_at:'2026-10-01T05:01:30Z',current_time:at}];
 else throw Error('Unexpected API call '+path);
 return Response.json(data);
};
await syncActivity(d,request,now);await syncActivity(d,request,now+60000);
assert.equal(callsRequested,4);const result=await readActivity(d,now+60000);assert.equal(result.rows[0].calls,2);assert.equal(result.rows[0].state,'idle');
assert.equal((await d.prepare('SELECT count(*) AS n FROM activity_incidents').first()).n,1,'Repeated poll must not duplicate alerts');
await d.prepare('INSERT INTO events VALUES(?,?,?)').bind('EV-work',new Date(now+120000).toISOString(),JSON.stringify({actorId:'e',actor:'Operator',text:'Сохранён заказ'})).run();
await syncActivity(d,request,now+120000);assert.ok((await d.prepare('SELECT ended_at FROM activity_incidents').first()).ended_at);
await assert.rejects(syncActivity(d,async()=>{throw Error('secret token must not be exposed')},now+180000));
const health=JSON.parse((await d.prepare("SELECT data FROM settings WHERE id='activity-health'").first()).data);assert.equal(health.ok,false);assert.ok(!health.message.includes('secret'));
d.close();console.log('Activity: schedules, live states, breaks, department isolation, pagination, UTC dates, idempotent alerts, recovery and outage checks passed');
