import assert from 'node:assert/strict';
import {defaultOrderPolicy as defaults,orderPolicySchema,orderDataEditingEnabled} from '../lib/order-policy.ts';
import {reworkDeadlineFrom,finalNoAnswerDeadline,reworkStage,confirmationStage,allowedOrderTransitions} from '../lib/crm.ts';
const at='2026-10-02T09:00:00.000Z',now=Date.parse(at);
assert.equal(reworkDeadlineFrom(at),'2026-10-06T09:00:00.000Z');
assert.equal(reworkDeadlineFrom(at,2),'2026-10-02T11:00:00.000Z');
assert.equal(reworkDeadlineFrom(at,null),undefined);
const order={status:'confirm',finalHandoffAt:at,contact:'none'};
assert.equal(finalNoAnswerDeadline(order,'missed',at),'2026-10-03T09:00:00.000Z');
assert.equal(finalNoAnswerDeadline({...order,finalConfirmHours:3},'callback',at),'2026-10-02T12:00:00.000Z');
assert.equal(finalNoAnswerDeadline({...order,finalConfirmHours:null},'none',at),undefined);
assert.ok(!allowedOrderTransitions({...order,finalConfirmHours:null},'logistic').includes('rework'));
const changed={...defaults,reworkWarningHours:2,finalWarningHours:1,operatorDraftEdit:false,operatorReworkEdit:false,logisticDetailsEdit:false};
assert.equal(reworkStage({contact:'none',reworkDeadline:reworkDeadlineFrom(at,3)},now,changed),'new');
assert.equal(confirmationStage({...order,finalConfirmHours:2},now,changed),'new');
assert.equal(confirmationStage({...order,finalConfirmHours:1},now,changed),'expiring');
for(const role of ['operator','logistic','chief_logistic'])assert.equal(orderDataEditingEnabled(role,'draft',changed),false);
assert.equal(orderDataEditingEnabled('operator','rework',changed),false);
assert.equal(orderDataEditingEnabled('admin','draft',changed),true);
assert.equal(orderPolicySchema.safeParse({...defaults,reworkHours:0}).success,false);
assert.equal(orderPolicySchema.safeParse({...defaults,finalHours:1.5}).success,false);
assert.equal(orderPolicySchema.safeParse({...defaults,finalHours:null}).success,true);
console.log('Order policy: defaults, disabled and custom timers, warning thresholds, final handoff restrictions and editing switches passed.');

assert.equal(orderPolicySchema.parse({...defaults,confirmationHours:undefined,extraConfirmationHours:undefined}).confirmationHours,48);
assert.equal(orderPolicySchema.safeParse({...defaults,confirmationHours:0}).success,false);
assert.equal(orderPolicySchema.safeParse({...defaults,extraConfirmationHours:1.5}).success,false);
