import {reworkStage} from '../lib/crm.ts';
import assert from 'node:assert/strict';
import {employeeTasks} from '../lib/reminder-tasks.ts';
const at='2026-10-07T10:00:00Z',future='2026-10-07T11:00:00Z',now=Date.parse(at);
const operator={id:'op',role:'operator',department:'1',name:'Оператор'},head={id:'head',role:'department_head',department:'1'},otherHead={id:'other-head',role:'department_head',department:'2'},admin={id:'admin',role:'admin'},logistic={id:'log',role:'logistic'},chief={id:'chief',role:'chief_logistic'},courier={id:'courier',role:'courier'},redemption={id:'redemption',role:'redemption'};
const employees=[operator,head,otherHead,admin,logistic,chief,courier,redemption];
const client={id:'client',name:'Клиент',owner:'op'},base={id:'order',clientId:client.id,manager:'op',status:'rework',delivery:'cdek_pickup',reason:'У клиента вопросы',contact:'none',due:'',createdAt:at,updatedAt:at,round:1};
const events=Array.from({length:100},(_,i)=>({id:'event-'+i,kind:'courier',title:'Логист подтвердил заказ',at,orderId:base.id,readAt:i%2?at:undefined}));
const state=o=>({orders:[o],clients:[client],employees,events:[],reminders:events,settings:{}});
const tasks=(e,o=base)=>employeeTasks(state(o),e,now);
assert.equal(tasks(operator).length,1);assert.equal(tasks(head).length,1);assert.equal(tasks(otherHead).length,0);assert.equal(tasks(admin).length,0);
assert.equal(tasks(logistic).length,0);assert.equal(tasks(courier).length,0);
assert.deepEqual(employeeTasks({...state(base),reminders:events.map(r=>({...r,readAt:at}))},operator,now),tasks(operator),'Reading every informational event does not change the task');
assert.equal(tasks(operator,{...base,status:'confirm'}).length,0);
for(const e of [logistic,chief])assert.equal(tasks(e,{...base,status:'confirm'}).length,1);
assert.equal(tasks(admin,{...base,status:'check'}).length,1);assert.equal(tasks(logistic,{...base,status:'check'}).length,0);
for(const status of ['shipping','redeemed','refused'])assert.equal(tasks(operator,{...base,status}).length,0);
assert.equal(tasks(redemption,{...base,status:'pickup'}).length,1);
const call={...base,contact:'callback',due:future,contactAuthor:{name:'Оператор',at}};
assert.equal(tasks(operator,call).length,1);assert.equal(tasks(operator,call)[0].kind,'call','Call replaces the generic rework task');
assert.equal(tasks(operator,call)[0].due,future);assert.match(employeeTasks(state(call),operator,Date.parse(future))[0].title,/Пора позвонить/);
const assigned={...base,delivery:'moscow_courier',status:'packing',courier:{id:'courier',name:'Курьер',phase:'pending',assignedAt:at,amount:10000}};
assert.equal(tasks(courier,assigned).length,1);assert.equal(tasks(logistic,assigned).length,0);
const confirmation={...assigned,courier:{...assigned.courier,phase:'confirmation',acceptedAt:at,workStartedAt:at,workHours:48}};
assert.equal(tasks(courier,confirmation).length,1);assert.equal(tasks(operator,confirmation).length,0);
const wait={...assigned,status:'rework',courier:{...confirmation.courier,phase:'operator',operatorStartedAt:at}};
assert.equal(tasks(courier,wait).length,0);assert.equal(tasks(operator,wait).length,1);
const urgent={...wait,courier:{...wait.courier,doorRefusal:{at,claimDueAt:at,decisionDueAt:future}}};
assert.equal(reworkStage(urgent,now),'new','Urgent doorstep work stays in New regardless of the normal timer or call filter');
for(const e of [operator,head,admin]){assert.equal(tasks(e,urgent).length,1);assert.equal(tasks(e,urgent)[0].kind,'courier-door');}
for(const e of [courier,logistic,otherHead])assert.equal(tasks(e,urgent).length,0);
const paid={...assigned,status:'redeemed',redeemedAt:at};
assert.equal(tasks(courier,paid).length,1);assert.equal(tasks(logistic,paid).length,1);
assert.equal(tasks(courier,{...paid,paymentReceivedAt:at}).length,0,'Receipt is an informational event');
assert.equal(tasks(logistic,{...paid,paymentReceivedAt:at}).length,0);
const recall={...confirmation,courier:{...confirmation.courier,phase:'recall_returned',recall:{requestedAt:at,returnedAt:at}}};
assert.equal(tasks(courier,recall).length,0);assert.equal(tasks(logistic,recall).length,1);
const repack={...wait,courierRepackRequest:{at,reason:'Изменить корзину'}};
assert.equal(tasks(operator,repack).length,0);assert.equal(tasks(logistic,repack).length,1);
const atWarehouse={...repack,status:'packing',courier:undefined,courierRecall:{completedAt:at,returnedAt:at}};
assert.equal(tasks(operator,atWarehouse).length,1);assert.equal(tasks(logistic,atWarehouse).length,0);
assert.equal(tasks(logistic,{...atWarehouse,courierRepackRequest:{...repack.courierRepackRequest,completedAt:at}}).length,1);
assert.equal(tasks(logistic,{...base,status:'shipping',cdekExported:true,cdekWaybillReceived:false}).length,1);
assert.equal(tasks(logistic,{...base,status:'shipping',cdekExported:true,cdekWaybillReceived:true}).length,0);
assert.equal(tasks(logistic,{...base,status:'packing',cdekDeleting:true}).length,0);
const requests={...state({...base,status:'shipping'}),clients:[{...client,orderRequest:{id:'r',status:'pending',actorId:'op',manager:'op',department:'1',at}}]};
assert.equal(employeeTasks(requests,head,now).length,1);assert.equal(employeeTasks(requests,admin,now).length,1);assert.equal(employeeTasks(requests,otherHead,now).length,0);assert.equal(employeeTasks(requests,operator,now).length,0);
requests.clients[0].orderRequest.status='approved';assert.equal(employeeTasks(requests,head,now).length,0);assert.equal(employeeTasks(requests,operator,now).length,1);
requests.clients[0].orderRequest.status='rejected';assert.equal(employeeTasks(requests,operator,now).length,0);
const many={...state(base),orders:Array.from({length:50},(_,i)=>({...base,id:'order-'+i}))};
assert.equal(employeeTasks(many,operator,now).length,50,'Current tasks are not limited to 20 events');
console.log('Tasks: one per order, role/department boundaries, shared logistics, reading independence, callbacks, courier custody, exceptions, requests and 50-order queue passed.');
