import assert from 'node:assert/strict';
import {productSchema,productReady} from '../lib/warehouse.ts';
const draft={name:'Кроссовки',sku:'',weight:null,cost:15000,payment:15000};
assert(!productReady(productSchema.parse(draft)));
assert(productReady(productSchema.parse({...draft,sku:'SHOES-1',weight:500,payment:0})));
assert.throws(()=>productSchema.parse({...draft,weight:0}));
assert.throws(()=>productSchema.parse({...draft,sku:'x'.repeat(21)}));
assert.throws(()=>productSchema.parse({...draft,cost:-1}));
console.log('Warehouse validation passed');
const {parcelDefaults}=await import('../lib/warehouse.ts');
const product={...productSchema.parse({...draft,packedWeight:1.2,length:35,width:25,height:15}),id:'one',version:1};
assert.deepEqual(parcelDefaults([{name:'Кроссовки',quantity:1}],[product]),{weight:1.2,length:35,width:25,height:15,originMode:'warehouse',single:true});
assert.equal(parcelDefaults([{name:'Кроссовки',quantity:2}],[product]).weight,2.4);
assert.equal(parcelDefaults([{name:'Кроссовки',quantity:2}],[product]).length,null);
assert.equal(parcelDefaults([{name:'Unknown',quantity:1}],[product]),null);
console.log('Parcel defaults passed');
const {warehouseAddressSchema}=await import('../lib/warehouse.ts');
assert.deepEqual(warehouseAddressSchema.parse('127422'),{address:'127422',postalCode:'127422'});
assert.equal(warehouseAddressSchema.parse('Москва, 127422, ул. Примерная').postalCode,'127422');
assert.throws(()=>warehouseAddressSchema.parse('12742'));
assert.throws(()=>warehouseAddressSchema.parse('1234567'));
