'use client';
import {useState} from 'react';
import {normalizedPhone} from '@/lib/base-distribution';
import type {ImportRow} from '@/lib/base-import';
type Report={added:number;moved:number;skipped:number;duplicates:number;invalid:{row:number;phone:string;reason:string}[];conflicts:{phone:string;clientId:string;name:string;baseType:string}[];applied:boolean;backupId?:string};
export function BaseImport({base,actorId,revision,onDone}:{base:'M'|'J';actorId:string;revision:string;onDone:()=>void}){
 const [totals,setTotals]=useState({added:0,moved:0,skipped:0,duplicates:0,invalid:0});
 const [session,setSession]=useState(()=>crypto.randomUUID());
 const [rows,setRows]=useState<ImportRow[]>([]),[filename,setFilename]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[report,setReport]=useState<Report|null>(null),[choices,setChoices]=useState<Record<string,'M'|'J'>>({}),[fileDuplicates,setFileDuplicates]=useState(0),[offset,setOffset]=useState(0);
 async function read(file:File){setBusy(true);setError('');setReport(null);setRows([]);setOffset(0);setChoices({});setTotals({added:0,moved:0,skipped:0,duplicates:0,invalid:0});setSession(crypto.randomUUID());try{if(!/\.xlsx$/i.test(file.name)||file.size>25*1024*1024)throw Error('Выберите .xlsx до 25 МБ');const ExcelJS=(await import('exceljs')).default,book=new ExcelJS.Workbook();await book.xlsx.load(await file.arrayBuffer());
 const links=new Map<string,Set<string>>();const sheet=book.getWorksheet('Связанные номера');sheet?.eachRow((row,n)=>{if(n===1)return;const a=normalizedPhone(row.getCell(1).text),b=normalizedPhone(row.getCell(2).text);if(!a||!b)return;const group=new Set([a,b,...links.get(a)||[],...links.get(b)||[]]);for(const phone of group)links.set(phone,group);});
 const output:ImportRow[]=[],seen=new Set<string>();let duplicates=0;
 book.eachSheet(sh=>{if(sh.name==='Связанные номера')return;const headers:string[]=[];sh.getRow(1).eachCell((cell,col)=>{headers[col]=cell.text.trim();});const phone=headers.findIndex(h=>['телефон','номер телефона','phone','мобильный телефон'].includes(h?.toLowerCase())),name=headers.findIndex(h=>['фио','имя','клиент','name','фио клиента'].includes(h?.toLowerCase()));if(phone<1&&sh.rowCount>1)throw Error(`На листе «${sh.name}» нет столбца «Телефон» в первой строке`);
 sh.eachRow((row,n)=>{if(n===1)return;const raw=row.getCell(phone).text,normalized=normalizedPhone(raw),linked=[...links.get(normalized)||[]];if(normalized&&[normalized,...linked].some(p=>seen.has(p))){duplicates++;return;}[normalized,...linked].filter(Boolean).forEach(p=>seen.add(p));const fields:Record<string,string>={};row.eachCell((cell,col)=>{fields[headers[col]||`Столбец ${col}`]=cell.text;});fields['Исходный лист']=sh.name;output.push({row:n,phone:raw,name:name>0?row.getCell(name).text:'',linkedPhones:linked,fields});});});
 setRows(output);setFileDuplicates(duplicates);setFilename(file.name);
 }catch(e){setError(e instanceof Error?e.message:'Не удалось прочитать файл');}finally{setBusy(false);}}
 async function process(apply:boolean){setBusy(true);setError('');try{let batch=rows.slice(offset,offset+1000);while(JSON.stringify(batch).length>1300000&&batch.length>1)batch=batch.slice(0,Math.floor(batch.length/2));const r=await fetch(`/api/base?actorId=${encodeURIComponent(actorId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'import',session,offset,base,rows:batch,choices,apply,filename,revision})});const data=await r.json() as Report&{error?:string};if(!r.ok)throw Error(data.error);setReport(data);if(data.applied){setTotals(t=>({added:t.added+data.added,moved:t.moved+data.moved,skipped:t.skipped+data.skipped,duplicates:t.duplicates+data.duplicates,invalid:t.invalid+data.invalid.length}));setOffset(offset+batch.length);onDone();}}catch(e){setError(e instanceof Error?e.message:'Ошибка импорта');}finally{setBusy(false);}}
 return <div className="stack"><label className="field"><span>Excel-файл новых клиентов</span><input type="file" accept=".xlsx" disabled={busy} onChange={e=>{if(e.target.files?.[0])void read(e.target.files[0]);}}/><small>Первая строка — заголовки; нужен «Телефон», имя берётся из «ФИО». На листе «Связанные номера»: основной телефон в первом столбце, дополнительный — во втором. Исходный файл не изменяется.</small></label>{rows.length>0&&<><p>Строк после удаления дублей: {rows.length}. Дублей в файле: {fileDuplicates}. Обработано: {Math.min(offset,rows.length)}.</p>{offset>0&&<p className="notice">Итого: добавлено {totals.added}, перенесено {totals.moved}, пропущено существующих {totals.skipped}, дублей {fileDuplicates+totals.duplicates}, неверных телефонов {totals.invalid}.</p>}<p className="muted">Импорт по 1000 строк. Перед первой частью сохраняется полная копия клиентской базы. Для каждой части сохраняется журнал изменений для восстановления.</p>{offset<rows.length&&<button className="secondary" disabled={busy} onClick={()=>void process(false)}>Проверить следующие {Math.min(1000,rows.length-offset)} строк</button>}</>}{report&&<section className="stack"><p>{report.applied?'Применено':'Предварительный результат'}: новых {report.added}, переносов {report.moved}, пропущено {report.skipped}, повторов {report.duplicates}, ошибок {report.invalid.length}.</p>{report.backupId&&<small>Копия перед изменениями: {report.backupId}</small>}{report.conflicts.map(c=><label className="field" key={c.clientId}><span>{c.name} · {c.phone} уже в базе {c.baseType==='J'?'Ж':'М'}. Где оставить?</span><select value={choices[c.clientId]||''} onChange={e=>setChoices({...choices,[c.clientId]:e.target.value as 'M'|'J'})}><option value="">Выберите базу</option><option value="M">М</option><option value="J">Ж</option></select></label>)}{!!report.invalid.length&&<details><summary>Пропущенные строки с причиной</summary>{report.invalid.map((r,i)=><p key={i}>Строка {r.row} · {r.phone||'нет телефона'} — {r.reason}</p>)}</details>}{!report.applied&&<button className="primary" disabled={busy||report.conflicts.some(c=>!choices[c.clientId])} onClick={()=>void process(true)}>Применить импорт</button>}</section>}{error&&<p role="alert">{error}</p>}{busy&&<p>Обработка…</p>}</div>;
}
