'use client';
import {useEffect,useState} from 'react';
import {Pencil} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {departments} from '@/lib/crm';
type Config={phones:string[];departments:Record<string,string>;revision:string};
export function CallbackPhones({actorId}:{actorId:string}){
 const [open,setOpen]=useState(false),[config,setConfig]=useState<Config|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;let cancelled=false;setConfig(null);setError('');fetch('/api/callback-phones').then(async r=>{const d=await r.json() as Config&{error?:string};if(!r.ok)throw Error(d.error);if(!cancelled)setConfig(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[open]);
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/callback-phones',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...config,actorId})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <><button type="button" className="secondary" style={{display:'inline-flex',marginLeft:16,padding:10,verticalAlign:'middle'}} aria-label="Настроить номера для обратной связи" title="Номера для обратной связи" onClick={()=>setOpen(true)}><Pencil size={20}/></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Номера для обратной связи</DialogTitle><DialogDescription>В накладную на сборку попадёт номер отдела ответственного оператора.</DialogDescription></DialogHeader>{config?<form className="stack" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="stack order-fields">{config.phones.map((phone,i)=><label className="field" key={i}><span>Номер {i+1}</span><input type="tel" value={phone} placeholder="+7 …" maxLength={30} onChange={e=>setConfig({...config,phones:config.phones.map((v,n)=>n===i?e.target.value:v)})}/></label>)}{Object.entries(departments).map(([dept,label])=><label className="field" key={dept}><span>{label}</span><select value={config.departments[dept]||''} onChange={e=>setConfig({...config,departments:{...config.departments,[dept]:e.target.value}})}><option value="">Не назначен</option><option value="1">Номер 1{config.phones[0]?` · ${config.phones[0]}`:''}</option><option value="2">Номер 2{config.phones[1]?` · ${config.phones[1]}`:''}</option></select></label>)}<button className="primary" type="submit">{busy?'Сохранение…':'Сохранить'}</button></fieldset></form>:!error&&<p>Загрузка…</p>}{error&&<p role="alert">{error}</p>}</DialogContent></Dialog></>;
}
