"use client";
import {useEffect,useRef,useState} from 'react';
import {money,stamp} from '@/lib/crm';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
type Operation={id:string;kind:string;sender:string|null;recipient:string|null;amount:number;purpose:string;date:string;created_at:string;accepted_at:string|null;sender_name:string;recipient_name:string};
type CashData={balance:number;operations:Operation[];recipients:{id:string;name:string;login:string}[]};
export function Cash({actorId}:{actorId:string}){
 const [data,setData]=useState<CashData|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [kind,setKind]=useState('');const [amount,setAmount]=useState('');const [purpose,setPurpose]=useState('');const [recipient,setRecipient]=useState('');
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'});const [date,setDate]=useState(today);
 const [success,setSuccess]=useState('');
 const pending=data?.operations.filter(o=>o.kind==='transfer'&&!o.accepted_at&&o.recipient===actorId)||[];
 const outgoing=data?.operations.filter(o=>o.kind==='transfer'&&!o.accepted_at&&o.sender===actorId)||[];
 const labels:Record<string,string>={add:'Пополнить кассу',spend:'Списать деньги',transfer:'Перевести сотруднику'};
 function choose(value:string){setKind(value);setAmount('');setPurpose('');setRecipient('');setDate(today);setError('');setSuccess('');}
 const retry=useRef<{key:string;id:string}|null>(null);
 async function request(body?:unknown){const r=await fetch('/api/cash?actorId='+encodeURIComponent(actorId),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const value=await r.json() as CashData&{error?:string};if(!r.ok)throw Error(value.error||'Не удалось загрузить кассу');return value;}
 useEffect(()=>{let active=true;request().then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(e.message);});return ()=>{active=false;};},[actorId]);
 async function submit(id?:string){setBusy(true);setError('');setSuccess('');try{
  if(id){setData(await request({action:'accept',id}));setSuccess('Получение подтверждено. Деньги добавлены в вашу кассу.');}
  else {const operation={kind,amount:Number(amount),date,purpose:kind==='spend'?'Зарплата':kind==='transfer'?'Перевод другому сотруднику':purpose,...(kind==='transfer'?{recipient}:{})};const key=JSON.stringify(operation);if(retry.current?.key!==key)retry.current={key,id:crypto.randomUUID()};setData(await request({action:'create',operation:{...operation,id:retry.current.id}}));retry.current=null;setAmount('');setPurpose('');setSuccess(kind==='transfer'?'Перевод создан. Деньги списаны из вашей кассы и ожидают подтверждения получателя.':kind==='spend'?'Деньги списаны. Операция сохранена в истории.':'Касса пополнена. Операция сохранена в истории.');setKind('');}
 }catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <section className="stack table-panel cash-panel"><div className="toolbar"><div><h2>Моя касса</h2><p className="muted">Ваши деньги и переводы сотрудникам</p></div><button className="secondary" disabled={busy} onClick={()=>{setError('');request().then(setData).catch(e=>setError(e.message));}}>Обновить</button></div>
 <div className="cash-summary"><div className="cash-balance"><span>Доступно в кассе</span><strong>{data?money(data.balance/100):'Загрузка…'}</strong><small>Эту сумму можно списать или перевести.</small></div><div><span>Вам передают</span><strong>{money(pending.reduce((n,o)=>n+o.amount,0)/100)}</strong><small>Добавится в кассу после получения денег.</small></div><div><span>Вы передали</span><strong>{money(outgoing.reduce((n,o)=>n+o.amount,0)/100)}</strong><small>Уже списано. Получатели ещё не подтвердили.</small></div></div>
 {error&&<p role="alert" className="notice amber">{error}</p>}{success&&<p role="status" className="notice">{success}</p>}
 {pending.length>0&&<section className="cash-pending stack"><h3>Подтвердите деньги, которые вам привезли</h3><p>Нажимайте «Деньги получены» только после фактического получения.</p>{pending.map(o=><div className="cash-pending-row" key={o.id}><div><b>{money(o.amount/100)}</b><p>От: {o.sender_name}</p><small>{o.date.split('-').reverse().join('.')} · Ожидает получения</small></div><button className="primary" disabled={busy} onClick={()=>void submit(o.id)}>Деньги получены · {money(o.amount/100)}</button></div>)}</section>}
 <div><h3>Что вы хотите сделать?</h3><div className="cash-actions">{[['add','+','Пополнить','Внести деньги или начальный остаток'],['spend','−','Списать','Зафиксировать выплату зарплаты'],['transfer','→','Перевести','Передать деньги другому сотруднику']].map(([value,icon,title,description])=><button type="button" key={value} className="cash-action" aria-pressed={kind===value} aria-expanded={kind===value} aria-controls="cash-operation-form" disabled={busy||!data} onClick={()=>choose(value)}><span className="cash-action-icon" aria-hidden="true">{icon}</span><b>{title}</b><small>{description}</small></button>)}</div></div>
 {kind&&<form id="cash-operation-form" className="stack cash-form" onSubmit={e=>{e.preventDefault();void submit();}}><h3>{labels[kind]}</h3><p className="muted">{kind==='add'?'Укажите сумму, которую вносите в свою кассу.':kind==='spend'?'Сумма будет списана с вашего баланса как выплата зарплаты.':'Выберите, кому передаёте деньги. Сумма спишется у вас сразу, а у получателя появится после его подтверждения.'}</p><div className="form-grid">
 {kind==='transfer'&&<label>Кому передаёте деньги<select required value={recipient} disabled={busy} onChange={e=>setRecipient(e.target.value)}><option value="">Выберите сотрудника</option>{data?.recipients.map(e=><option value={e.id} key={e.id}>{e.name} · {e.login}</option>)}</select></label>}
 <label>Сумма, ₽<input type="number" step="0.01" min="0.01" max={kind==='add'?100000000:(data?.balance||0)/100} required autoFocus value={amount} placeholder="0,00" disabled={busy} onChange={e=>setAmount(e.target.value)}/></label>
 {kind==='spend'&&<label>Назначение платежа<input value="Зарплата" readOnly/></label>}
 {kind==='add'&&<label>Откуда поступили деньги<input required maxLength={500} value={purpose} disabled={busy} onChange={e=>setPurpose(e.target.value)} placeholder="Например, начальный остаток"/></label>}
 <label>{kind==='spend'?'Дата списания':kind==='transfer'?'Дата передачи':'Дата пополнения'}<input type="date" max={today} required value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label>
 </div>{kind!=='add'&&<small>Доступно: {money((data?.balance||0)/100)}</small>}<div className="action-buttons"><button className="primary" disabled={busy||!data||kind!=='add'&&(data?.balance||0)<=0}>{busy?'Сохранение…':kind==='add'?'Внести деньги в кассу':kind==='spend'?'Списать на зарплату':'Создать перевод'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setKind('')}>Отмена</button></div></form>}
 <h3>История операций</h3><Table><TableHeader><TableRow><TableHead>Дата операции</TableHead><TableHead>Назначение</TableHead><TableHead>Отправитель / получатель</TableHead><TableHead>Сумма</TableHead><TableHead>Получение</TableHead></TableRow></TableHeader><TableBody>{data?.operations.map(o=>{const incoming=o.recipient===actorId;const pending=o.kind==='transfer'&&!o.accepted_at;return <TableRow key={o.id} style={pending?{background:'#f1f3f5',color:'#64748b'}:undefined}><TableCell>{o.date.split('-').reverse().join('.')}<small className="block muted">Записано: {stamp(o.created_at)}</small></TableCell><TableCell>{o.purpose}</TableCell><TableCell>{incoming?o.sender_name||'Пополнение':o.recipient_name||'Выдача из кассы'}</TableCell><TableCell>{incoming?'+':'−'}{money(o.amount/100)}</TableCell><TableCell>{pending?<><span>В пути · ожидает получения</span></>:o.accepted_at?`${o.kind==='spend'?'Списано':!incoming?'Получатель подтвердил':'Зачислено'} ${stamp(o.accepted_at)}`:'—'}</TableCell></TableRow>;})}</TableBody></Table>{data&&!data.operations.length&&<p className="muted">Операций пока нет. Начальный баланс — 0 ₽.</p>}
 </section>;
}
