'use client';
import {useEffect,useState} from 'react';
import {cdekStatuses,type CdekMapping} from '@/lib/cdek-statuses';
import {orderGroups} from '@/lib/crm';
export function CdekStatusMapping({actorId,isAdmin}:{actorId:string;isAdmin:boolean}){
 const [mapping,setMapping]=useState<CdekMapping>({}),[revision,setRevision]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 async function load(){setReady(false);setMessage('');try{const r=await fetch('/api/cdek/status-mapping');const d=await r.json() as {mapping:CdekMapping;revision:string;error?:string};if(!r.ok)throw Error(d.error);setMapping(d.mapping);setRevision(d.revision);setDirty(false);setReady(true);}catch{setMessage('Не удалось загрузить настройки. Повторите загрузку.');}}
 useEffect(()=>{void load();},[]);
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/cdek/status-mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actorId,mapping,revision})});const d=await r.json() as {revision:string;error?:string};if(!r.ok)throw Error(d.error);setRevision(d.revision);setDirty(false);setMessage('Соответствия сохранены.');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <section className="cdek-status-settings"><h3>Статусы СДЭК → статусы CRM</h3><p>Общие правила для всех четырёх аккаунтов. Выберите наш статус напротив каждого статуса СДЭК.</p><p className="muted">Правила применяются при открытии карточки отправления, затем каждую минуту, пока она открыта, и по кнопке обновления статуса.</p><label className="field"><span>Найти статус СДЭК</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название или код статуса"/></label><div className="cdek-status-list">{cdekStatuses.filter(s=>(s.label+' '+s.code).toLowerCase().includes(query.toLowerCase())).map(s=><div className="cdek-status-row" key={s.code}><div><b title={s.description}>{s.label}</b><small>{s.code}</small>{s.code.startsWith('RETURNED_TO_')&&<small>Не означает возврат покупателя</small>}</div><select aria-label={`Статус CRM для «${s.label}»`} title={s.description} disabled={!isAdmin||!ready||busy} value={mapping[s.code]||''} onChange={e=>{setMapping(m=>({...m,[s.code]:e.target.value as CdekMapping[string]}));setDirty(true);setMessage('');}}><option value="">Не менять</option>{orderGroups.map(g=><option value={g.id} key={g.id}>{g.label}</option>)}</select></div>)}</div><p className="muted">«Вручён» означает получение посылки клиентом. Перечисление наложенного платежа на ваш счёт — отдельное событие.</p>{!ready&&<button className="secondary" onClick={load}>Повторить загрузку</button>}{isAdmin&&<button className="primary" disabled={!ready||busy||!dirty} onClick={save}>{busy?'Сохранение…':'Сохранить соответствия'}</button>}<p role="status">{message|| (dirty?'Есть несохранённые изменения':'')}</p></section>;
}
