'use client';
import {CdekStatusMapping} from './cdek-status-mapping';
import {useEffect,useState} from 'react';
type Account={slot:number;name:string;configured:boolean;checkedAt?:string};
export function CdekSettings({actorId,isAdmin}:{actorId:string;isAdmin:boolean}){
 const [accounts,setAccounts]=useState<Account[]>([]),[slot,setSlot]=useState(1),[name,setName]=useState('СМ'),[clientId,setClientId]=useState(''),[clientSecret,setClientSecret]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/cdek').then(async r=>{if(!r.ok)throw Error();setAccounts(((await r.json()) as {accounts:Account[]}).accounts);}).catch(()=>setMessage('Не удалось загрузить аккаунты СДЭК'));},[]);
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/cdek',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actorId,slot,name,clientId,clientSecret})});const data=await r.json() as Account & {error?:string};if(!r.ok)throw Error(data.error);setAccounts(a=>[...a.filter(x=>x.slot!==slot),data]);setClientId('');setClientSecret('');setMessage('Авторизация проверена. Аккаунт сохранён.');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось проверить подключение');}finally{setBusy(false);}}
 const current=accounts.find(a=>a.slot===slot);
 return <section className="integration" style={{display:'block'}}><h3>СДЭК</h3><p>Подключено аккаунтов: {accounts.filter(a=>a.configured).length} из 4</p><label>Аккаунт<select value={slot} disabled={busy} onChange={e=>{const n=Number(e.target.value);setSlot(n);setName(accounts.find(a=>a.slot===n)?.name||(n===1?'СМ':`Аккаунт ${n}`));setClientId('');setClientSecret('');setMessage('');}}>{[1,2,3,4].map(n=><option key={n} value={n}>{accounts.find(a=>a.slot===n)?.name||(n===1?'СМ':`Аккаунт ${n}`)}</option>)}</select></label><p>{current?.configured?'Авторизация проверена':'Не подключён'} · Основной API СДЭК</p>{isAdmin&&<div className="form-grid"><label>Название<input value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>Ключ<input type="password" autoComplete="new-password" value={clientId} disabled={busy} placeholder={current?.configured?'Сохранён':'Введите ключ'} onChange={e=>setClientId(e.target.value)}/></label><label>Пароль<input type="password" autoComplete="new-password" value={clientSecret} disabled={busy} placeholder={current?.configured?'Сохранён':'Введите пароль'} onChange={e=>setClientSecret(e.target.value)}/></label><button className="secondary" disabled={busy||!name.trim()} onClick={save}>{busy?'Проверка…':'Проверить и сохранить'}</button></div>}<p role="status">{message}</p><CdekStatusMapping actorId={actorId} isAdmin={isAdmin}/></section>;
}
