'use client';
import {requestCdekPrint} from '@/lib/cdek-print-client';
import {useEffect,useRef,useState} from 'react';
import type {Order} from '@/lib/crm';
import type {Shipment,ShipmentForm} from '@/lib/cdek-shipment';
type Point={sameStreet?:boolean;samePostalCode?:boolean;code:string;address:string;workTime:string;allowedCod:boolean};
type Item={name:string;quantity:number;sku?:string;weight?:number;cost?:number;payment?:number};
export function CdekShipment({order,actorId,disabled,onUpdated}:{order:Order;actorId:string;disabled:boolean;onUpdated:()=>void}){
 const [shipment,setShipment]=useState<Shipment|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[items,setItems]=useState<Item[]>([]);
 const [form,setForm]=useState<ShipmentForm>({shipmentPoint:'',deliveryPoint:'',senderAddress:'',payment:'cod',deliveryCost:0});
 const [recipientPoints,setRecipientPoints]=useState<Point[]>([]),[recoveryUuid,setRecoveryUuid]=useState('');
 const requestRunning=useRef(false);
 const [packed,setPacked]=useState(false);
 const query=new URLSearchParams({actorId,orderId:order.id}).toString();
 const tariff=order.cdekTariff;const canCreate=!!tariff&&['packing','phone'].includes(order.status)&&(!shipment||shipment.state==='invalid');
 useEffect(()=>{let cancelled=false;fetch(`/api/cdek/shipment?${query}`).then(async r=>{const d=await r.json() as {error?:string;shipment?:Shipment;items:Item[];warehouseAddress:string;warehouseShipmentPoint?:{code:string;address:string};points:Point[];message?:string;changed?:boolean};if(!r.ok)throw Error(d.error||"Ошибка СДЭК");if(cancelled)return;setShipment(d.shipment||null);setItems(d.items);setForm(d.shipment?.form||{shipmentPoint:d.warehouseShipmentPoint?.code||'',deliveryPoint:'',senderAddress:d.warehouseAddress||'',payment:'cod',deliveryCost:0});}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[query]);
 async function points(side:'sender'|'recipient'){
  setBusy(true);setError('');try{const r=await fetch(`/api/cdek/shipment?${query}&points=${side}`);const d=await r.json() as {error?:string;shipment?:Shipment;items:Item[];warehouseAddress:string;points:Point[];message?:string;changed?:boolean};if(!r.ok)throw Error(d.error);setRecipientPoints(d.points);if(!d.points.length)setMessage('По этому индексу ПВЗ не найдены. Проверьте индекс в расчёте доставки.');}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить ПВЗ');}finally{setBusy(false);}
 }
 async function action(action:'create'|'refresh'|'print'){
  if(requestRunning.current)return;requestRunning.current=true;
  setBusy(true);setError('');setMessage('');try{
   const r=await (action==='print'?requestCdekPrint({actorId,orderId:order.id}):fetch('/api/cdek/shipment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,actorId,orderId:order.id,version:order.version,form,...(recoveryUuid?{recoveryUuid}:{})})}));
   if(r.ok&&r.headers.get('content-type')?.includes('application/pdf')){const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`СДЭК-${shipment?.number||order.id}.pdf`;a.click();setShipment(x=>x?{...x,downloadedAt:new Date().toISOString()}:x);onUpdated();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
   const d=await r.json() as {error?:string;shipment?:Shipment;items:Item[];warehouseAddress:string;points:Point[];message?:string;changed?:boolean};if(!r.ok)throw Error(d.error);if(d.shipment){setShipment(d.shipment);}if(d.message)setMessage(d.message);if(d.changed)onUpdated();
  }catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить действие');}finally{requestRunning.current=false;setBusy(false);}
 }
 useEffect(()=>{if(!shipment?.uuid||shipment.state==='invalid'||disabled)return;void action('refresh');const timer=setInterval(()=>{void action('refresh');},60000);return()=>clearInterval(timer);},[shipment?.uuid,disabled]);
 const patch=(value:Partial<ShipmentForm>)=>{setForm(x=>({...x,...value}));};
 const payment=items.reduce((n,i)=>n+(form.payment==='prepaid'?0:(i.payment||0))*i.quantity,0)+form.deliveryCost;
 const pointField=(side:'sender'|'recipient')=>{const list=recipientPoints;const key=side==='sender'?'shipmentPoint':'deliveryPoint';return <div className="field"><span>{side==='sender'?'ПВЗ сдачи посылки':'ПВЗ получателя'}</span><button type="button" className="secondary" onClick={()=>points(side)} aria-label={side==='sender'?'Загрузить ПВЗ сдачи':'Загрузить ПВЗ получателя'}>Загрузить ПВЗ</button><select aria-label={side==='sender'?'ПВЗ сдачи посылки':'ПВЗ получателя'} value={form[key]} onChange={e=>patch({[key]:e.target.value})}><option value="">Выберите пункт</option>{form[key]&&!list.some(x=>x.code===form[key])&&<option value={form[key]}>{form[key]}</option>}{list.map(p=><option key={p.code} value={p.code} disabled={side==='recipient'&&payment>0&&!p.allowedCod}>{p.sameStreet?'На улице клиента · ':p.samePostalCode?'Индекс клиента · ':''}{p.code} · {p.address} · {p.workTime}{!p.allowedCod?' · без наложенного платежа':''}</option>)}</select></div>;};
 return <section id="cdek-shipment-guide" className="stack"><h3>Отправление СДЭК</h3>{loading?<p>Загрузка отправления…</p>:<>
 {shipment&&<div className="notice"><span><b>{{sending:'Запрос отправляется',pending:'СДЭК обрабатывает заказ',ready:'Заказ зарегистрирован в СДЭК',invalid:'СДЭК отклонил заказ',unknown:'Результат отправки требует проверки'}[shipment.state]}</b>{shipment.number&&<><br/>Накладная СДЭК № {shipment.number}</>}<br/>Аккаунт: {shipment.account}{shipment.uuid&&<><br/>UUID: {shipment.uuid}</>}{shipment.error&&<p role="alert">{shipment.error}</p>}</span></div>}
 {!tariff&&!shipment&&<p className="muted">Сначала рассчитайте доставку и выберите тариф.</p>}
 {canCreate&&<fieldset disabled={disabled||busy} className="stack order-fields"><p>{tariff!.account} · {tariff!.name} · {tariff!.amount.toLocaleString('ru-RU')} ₽</p><div className="form-grid">{tariff!.params.originMode==='warehouse'?null:<label className="field"><span>Полный адрес склада</span><input value={form.senderAddress} onChange={e=>patch({senderAddress:e.target.value})}/></label>}{order.delivery==='cdek_pickup'?pointField('recipient'):<p>Курьер получателю: {order.address}</p>}<label className="field"><span>Оплата товаров</span><select value={form.payment} onChange={e=>patch({payment:e.target.value as ShipmentForm['payment']})}><option value="cod">При получении — суммы из склада</option><option value="prepaid">Предоплата — не брать оплату за товары</option></select></label><label className="field"><span>Сбор за доставку с получателя, ₽</span><input type="number" min={0} step="0.01" value={form.deliveryCost} onChange={e=>patch({deliveryCost:Number(e.target.value)})}/></label></div><small className="muted">В СДЭК автоматически передаётся телефон из карточки клиента. Стоимость тарифа оплачивается по договору; сбор с получателя указывается отдельно.</small>
 {!order.packingWaybillAt&&<p className="notice">Сначала скачайте накладную на сборку во вкладке «Бланк».</p>}<label className="packing-ready"><input type="checkbox" checked={packed} onChange={e=>setPacked(e.target.checked)}/>Заказ собран и упакован</label>{order.delivery==='cdek_pickup'&&!form.deliveryPoint&&<p className="muted">Загрузите ПВЗ и выберите пункт получателя выше.</p>}<button type="button" className="primary" disabled={!order.packingWaybillAt||!packed||(order.delivery==='cdek_pickup'&&!form.deliveryPoint)} onClick={()=>action('create')}>Выгрузить заказ в СДЭК</button></fieldset>}
 {shipment&&shipment.state!=='invalid'&&<>{!shipment.uuid&&<label className="field"><span>UUID отправления из кабинета СДЭК для восстановления связи</span><input value={recoveryUuid} onChange={e=>setRecoveryUuid(e.target.value)}/></label>}<button type="button" className="secondary" disabled={busy||disabled||(!shipment.uuid&&!recoveryUuid)} onClick={()=>action('refresh')}>Обновить статус отправления</button>{shipment.state==='ready'&&<button type="button" className={shipment.downloadedAt?"secondary waybill-received":"primary cdek-button"} disabled={busy||disabled} onClick={()=>action('print')}>Накладная СДЭК</button>}</>}
 </>}{busy&&<p role="status">Обращаемся в СДЭК…</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="orange">{error}</p>}</section>;
}
