"use client";
import {useSessionTab} from "@/hooks/use-session-tab";
import {useState,useEffect} from 'react';
import {Toaster} from 'sonner';
import {money,stamp,type State,type Employee,type Order} from '@/lib/crm';
import {courierBalance,courierStage} from '@/lib/courier';
type Props={state:State;employee:Employee;busy:boolean;error:string;refresh:()=>Promise<void>;mutate:(p:Record<string,unknown>)=>Promise<boolean>};
export function CourierApp({state,employee,busy,error,refresh,mutate}:Props){
 const [tab,setTab]=useSessionTab<string>(`crm-navigation:${employee.id}:courier:tab`,'pending',['pending','delivery','money','return','settled']);const [query,setQuery]=useState('');const [action,setAction]=useState<{id:string;to:'redeemed'|'returned'}|null>(null);const [reason,setReason]=useState('');
 const [design,setDesign]=useState('aurora');
 useEffect(()=>{try{setDesign(localStorage.getItem(`courier-design:${employee.id}`)==='classic'?'classic':'aurora');}catch{}},[employee.id]);
 function changeDesign(value:string){setDesign(value);try{localStorage.setItem(`courier-design:${employee.id}`,value);}catch{}}
 const balance=courierBalance(state.orders,employee.id);
 const labels:Record<string,string>={pending:'Принять посылки',delivery:'На доставке',money:'Деньги на руках',return:'Вернуть на склад',settled:'Завершённые'};
 const orders=state.orders.filter(o=>courierStage(o)===tab&&`${o.id} ${state.clients.find(c=>c.id===o.clientId)?.name||''}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
 async function confirm(o:Order){if(!action)return;const ok=await mutate({action:'courierOutcome',id:o.id,version:o.version,to:action.to,reason,confirmed:true});if(ok){setAction(null);setReason('');}}
 return <main className={`courier-app courier-design-${design}`}><Toaster richColors position="top-center"/><div className="courier-design-picker" role="group" aria-label="Дизайн кабинета"><span>Дизайн</span><button type="button" aria-pressed={design==='classic'} onClick={()=>changeDesign('classic')}>Классический</button><button type="button" aria-pressed={design==='aurora'} onClick={()=>changeDesign('aurora')}>Аврора</button></div><div className="courier-hero"><header className="courier-header"><div><small>СМ · КУРЬЕР</small><h1>{employee.name}</h1></div><button className="secondary" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.replace('/login');}}>Выйти</button></header>
 <section className="courier-balances" aria-label="Мой отчёт"><div><span>Заказы на руках</span><strong>{money(balance.parcels)}</strong><small>Посылки на доставке и возвраты</small></div><div><span>Деньги на руках</span><strong>{money(balance.cash)}</strong><small>Нужно передать логисту</small></div><div><span>Ожидает приёма</span><strong>{money(balance.pending)}</strong><small>Ещё не входит в ваш отчёт</small></div><div className="courier-total"><span>Всего под отчётом</span><strong>{money(balance.total)}</strong></div></section></div>
 <div className="courier-refresh"><p>Возвраты и деньги снимаются с отчёта после подтверждения логистом.</p><button className="secondary" disabled={busy} onClick={()=>void refresh()}>Обновить</button></div>{error&&<p role="alert" className="notice amber">{error}. Проверьте соединение и обновите данные.</p>}
 <nav className="courier-tabs" aria-label="Мои заказы">{Object.entries(labels).map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setAction(null);}}>{label}<b>{state.orders.filter(o=>courierStage(o)===id).length}</b></button>)}</nav>
 <label className="courier-search">Поиск заказа<input type="search" placeholder="Номер заказа или имя клиента" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <section className="courier-orders" aria-label={labels[tab]}>{orders.map(o=>{const c=state.clients.find(c=>c.id===o.clientId);const stage=courierStage(o);const address=(o.address||c?.address||'').trim();return <article className="courier-order" key={o.id}><div className="courier-order-heading"><span>{o.id}</span><strong>{money(o.courier!.amount)}</strong></div><h2>{c?.name||'Клиент'}</h2><p className="courier-state">{stage==='pending'?'Ожидает приёма курьером':stage==='money'?'Оплачен · передайте деньги логисту':stage==='return'?'Возврат · ожидает приёма на склад':stage==='settled'?o.paymentReceivedAt?'Оплата принята логистом':'Возврат принят на склад':'Посылка у вас · ожидает доставки'}</p><p className="courier-address">{address||'Адрес не указан'}</p>{o.courier?.acceptedAt&&address&&<div className="courier-navigation"><a className="secondary courier-navigator" href={'yandexnavi://map_search?text='+encodeURIComponent(address)}><svg width="28" height="28" viewBox="0 0 32 32" aria-hidden="true"><rect width="32" height="32" rx="8" fill="#ffcf00"/><path d="M24 7 19 25 14 18 7 13Z" fill="#252525"/></svg>Яндекс Навигатор</a></div>}{o.courier?.acceptedAt&&c?.phone&&<a className="secondary courier-phone" href={'tel:'+c.phone.replace(/[^+\d]/g,'')}>Позвонить · {c.phone}</a>}{o.testOnly&&<p className="notice amber">ТЕСТОВЫЙ ЗАКАЗ — не доставлять.</p>}{o.comment&&<p><b>Комментарий:</b> {o.comment}</p>}{o.waybillComment&&<p><b>Для доставки:</b> {o.waybillComment}</p>}{o.status==='returned'&&o.reason&&<p><b>Причина возврата:</b> {o.reason}</p>}
 <details><summary>Товары и история заказа</summary><ul>{o.items.map((i,n)=><li key={n}>{i.name} × {i.quantity}</li>)}</ul><ol className="courier-history"><li>Логист передал заказ · {stamp(o.courier!.assignedAt)}<small>Ожидает подтверждения получения посылки</small></li>{o.courier!.acceptedAt&&<li>Принято курьером · {stamp(o.courier!.acceptedAt!)}<small>Заказы на руках +{money(o.courier!.amount)}</small></li>}{o.redeemedAt&&<li>Клиент оплатил · {stamp(o.redeemedAt)}<small>Заказы −{money(o.courier!.amount)} · деньги +{money(o.courier!.amount)}</small></li>}{o.returnedAt&&<li>Отмечен возврат · {stamp(o.returnedAt)}<small>Посылка остаётся под отчётом до приёма на склад</small></li>}{o.warehouseReturnedAt&&<li>Возврат на склад · {stamp(o.warehouseReturnedAt)}<small>Заказы на руках −{money(o.courier!.amount)} · заказ {o.id}</small></li>}{o.paymentReceivedAt&&<li>Логист принял оплату · {stamp(o.paymentReceivedAt)}<small>Деньги на руках −{money(o.courier!.amount)} · заказ {o.id}</small></li>}</ol></details>
 {stage==='pending'&&<div className="courier-confirm"><p>Проверьте номер заказа и посылку. Подтверждайте только после её фактического получения от логиста. Звонок клиенту и Яндекс Навигатор станут доступны после приёма.</p><button className="primary" disabled={busy} onClick={()=>void mutate({action:'courierAccept',id:o.id,version:o.version,confirmed:true})}>{busy?'Сохранение…':'Принять посылку'}</button></div>}
 {stage==='delivery'&&(action?.id===o.id?<div className="courier-confirm"><h3>{action.to==='redeemed'?'Деньги от клиента получены?':'Оформить возврат посылки?'}</h3><p>{action.to==='redeemed'?`Подтвердите получение полной суммы ${money(o.courier!.amount)}. После подтверждения её нужно передать логисту.`:'Заказ станет возвратом у оператора и логиста. Верните посылку на склад — до её приёма она остаётся под вашим отчётом.'}</p>{action.to==='returned'&&<label>Причина возврата<textarea required maxLength={1000} rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Почему клиент вернул посылку?"/></label>}<button className="primary" disabled={busy||action.to==='returned'&&!reason.trim()} onClick={()=>void confirm(o)}>{busy?'Сохранение…':action.to==='redeemed'?'Да, деньги получены':'Подтвердить возврат'}</button><button className="secondary" disabled={busy} onClick={()=>setAction(null)}>Назад</button></div>:<div className="courier-buttons"><button className="primary" disabled={busy} onClick={()=>{setAction({id:o.id,to:'redeemed'});setReason('');}}>Оплачен</button><button className="secondary" disabled={busy} onClick={()=>{setAction({id:o.id,to:'returned'});setReason('');}}>Возврат</button></div>)}
 </article>;})}{!orders.length&&<div className="empty"><h2>Здесь пока нет заказов</h2><p>{query?'Измените поисковый запрос.':'Заказы появятся после передачи логистом или смены этапа.'}</p></div>}</section>
 </main>;
}
