'use client';
import {useState} from 'react';
import {stamp,money,type Order,type Employee} from '@/lib/crm';
import {courierLabel,courierParcelLocation,courierPhase,courierDeadline,courierTimeLeft,courierWaitingSince,courierStage,canEditRecalledCourierOrder} from '@/lib/courier';

export function CourierWork({order:o,employee,busy,mutate}:{order:Order;employee:Employee;busy:boolean;mutate:(p:Record<string,unknown>)=>Promise<boolean>}){
 const [reason,setReason]=useState(''),[received,setReceived]=useState(false);
 const c=o.courier,phase=courierPhase(o),deadline=courierDeadline(o),stage=courierStage(o),request=o.courierRepackRequest;
 const needsRepack=!!request&&!request.completedAt;
 const logistic=['admin','logistic','chief_logistic'].includes(employee.role);
 const operator=(employee.role==='admin'||employee.role==='operator'&&o.manager===employee.id)&&phase==='operator'&&o.status==='rework';
 const act=(operation:string,extra:Record<string,unknown>={})=>void mutate({action:'courierWorkflow',operation,id:o.id,version:o.version,...extra});
 if(!c&&!o.courierRecall)return <section className="notice stack courier-work-panel"><strong>{courierLabel(o)}</strong><p>Посылка: {courierParcelLocation(o)}</p></section>;
 if(!c)return o.courierRecall&&['packing','rework'].includes(o.status)?<section className="notice stack courier-work-panel"><strong>{o.status==='rework'?'Заказ в работе у оператора · возврат после пересборки':'Заказ возвращён на сборку'}</strong><p>{o.courierRecall.reason}. Приём подтверждён {stamp(o.courierRecall.completedAt!,'Europe/Moscow')} МСК. {o.courierRecall.returnedAt?'Посылка снята с отчёта курьера, товары остаются в резерве заказа.':'Курьер ещё не принимал посылку. Заказ снова на сборке у логиста.'}</p>{o.status==='rework'&&<p>Посылка на складе. Свяжитесь с клиентом, затем верните заказ логисту на сборку или зафиксируйте отказ. Общий запас доработки не начинается заново.</p>}{needsRepack?<p><b>Ожидаются правки корзины:</b> {request.reason}. {canEditRecalledCourierOrder(o,employee)?'Откройте «Адрес и товары», внесите изменения и сохраните заказ.':'Оператор или администратор должен сохранить исправленный заказ. После этого можно подготовить новую накладную.'}</p>:<p>После возврата заказа на сборку логист подготовит новую накладную и передаст собранный заказ курьеру.</p>}</section>:<section className="notice stack courier-work-panel"><strong>{courierLabel(o)}</strong><p>Посылка: {courierParcelLocation(o)}</p></section>;
 return <section className="notice stack courier-work-panel"><strong>{courierLabel(o)}</strong><p>Посылка: {courierParcelLocation(o)}<br/>Курьер: {c.name} · {money(c.amount)}<br/>Передан: {stamp(c.assignedAt,'Europe/Moscow')} МСК</p>
 {!c.acceptedAt?<p>Ожидает приёма: {courierWaitingSince(o)}. {c.phase==='pending'?'Таймер подтверждения начнётся после фактического приёма посылки.':'Заказ уже подтверждён; после приёма курьер продолжит доставку.'}</p>:<p>Посылка принята: {stamp(c.acceptedAt,'Europe/Moscow')} МСК. {stage==='settled'?'Расчёт завершён.':'Посылка остаётся под отчётом курьера до сдачи денег или подтверждения физического приёма логистом.'}</p>}
 {deadline&&<p>До возврата оператору: <b>{courierTimeLeft(deadline)}</b> · {stamp(deadline,'Europe/Moscow')} МСК. Недозвон и перезвон срок не продлевают.</p>}
 {c.workReason&&phase==='operator'&&<p><b>Причина передачи:</b> {c.workReason}</p>}
 {c.operatorBudgetMs!==undefined&&<p>Общий запас доработки у оператора: <b>{c.operatorBudgetMs===null?'без ограничения':courierTimeLeft(o.reworkDeadline||new Date(Date.now()+c.operatorBudgetMs).toISOString())}</b>. {phase==='operator'?'Сейчас расходуется.':'Сейчас приостановлен.'} Повторная передача не восстанавливает запас.</p>}
 {c.postponement&&<p><b>{c.postponement.state==='pending'?'Запрошен перенос доставки':c.postponement.state==='approved'?'Доставка согласована':'Перенос отклонён'}:</b> {stamp(c.postponement.at,'Europe/Moscow')} МСК<br/>{c.postponement.reason}</p>}
 {needsRepack&&<p><b>Запрос на пересборку:</b> {request.reason}<br/>{request.name} · {stamp(request.at,'Europe/Moscow')} МСК. До отзыва логистом общий срок работы оператора продолжает идти.</p>}
 {c.recall&&<p><b>Отзыв на сборку:</b> {c.recall.reason}<br/>{c.recall.name} · {stamp(c.recall.requestedAt,'Europe/Moscow')} МСК</p>}
 {phase==='recall'&&<p>Ожидается физическая передача посылки курьером. Доставка и подтверждение остановлены.</p>}
 {logistic&&phase==='recall_returned'&&<><p>Курьер отметил передачу посылки. Подтвердите фактический приём: после этого посылка будет снята с его отчёта, заказ останется в «Курьер Москва → Новый».</p><label><input type="checkbox" checked={received} disabled={busy} onChange={e=>setReceived(e.target.checked)}/> Посылка фактически получена</label><button className="primary" disabled={busy||!received} onClick={()=>act('receiveRecall',{confirmed:true})}>Принять посылку на сборку</button></>}
 {operator&&<><p>Можно изменить адрес, комментарий и цену в «Адрес и товары». Для изменения товара или количества запросите пересборку.</p>{!needsRepack&&<><button className="primary" disabled={busy} onClick={()=>act('confirm')}>Вернуть курьеру — клиент готов выкупить</button><details><summary>Изменить товар или количество — запросить пересборку</summary><label>Что нужно изменить<textarea rows={2} maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} placeholder="Укажите товар и нужное количество"/></label><button className="secondary" disabled={busy||!reason.trim()} onClick={()=>act('requestRepack',{reason})}>Отправить запрос логисту</button></details></>}</>}
 {logistic&&!['none','settled','money'].includes(stage)&&!['returned','refused'].includes(o.status)&&!['recall','recall_returned'].includes(phase||'')&&<details open={needsRepack||undefined}><summary>{c.acceptedAt?'Запросить возврат посылки на сборку':'Отозвать заказ до приёма курьером'}</summary><p>{c.acceptedAt?'Курьеру придёт запрос. Посылка останется под его отчётом до подтверждения приёма логистом.':'Заказ вернётся в «Курьер Москва → Новый». Потребуется новая накладная на сборку.'}</p><label>Причина отзыва<textarea rows={2} maxLength={1000} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)} placeholder={request?.reason||'Что нужно исправить в заказе'}/></label><button className="secondary" disabled={busy||!(reason.trim()||needsRepack&&request.reason)} onClick={()=>act('recall',{reason:reason.trim()||request?.reason})}>{c.acceptedAt?'Запросить возврат на сборку':'Отозвать на сборку'}</button></details>}
 </section>;
}
