"use client";
import {useEffect,useState} from 'react';
import {money,stamp,roles,type Order} from '@/lib/crm';
import type {Operation} from '@/components/cash';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
type Account={id:string;name:string;login:string;role:keyof typeof roles;balance:number;pending:number;parcels?:number;accountable?:number};
export function EmployeeCash(){
 const [accounts,setAccounts]=useState<Account[]>([]);const [selected,setSelected]=useState<Account|null>(null);const [operations,setOperations]=useState<Operation[]>([]);
 const [courierOrders,setCourierOrders]=useState<Order[]>([]);
 const [error,setError]=useState('');const [historyError,setHistoryError]=useState('');const [loading,setLoading]=useState(true);const [historyLoading,setHistoryLoading]=useState(false);
 async function load(){setError('');setLoading(true);try{const r=await fetch('/api/cash?scope=all',{cache:'no-store'});const data=await r.json() as {accounts:Account[];error?:string};if(!r.ok)throw Error(data.error||'Не удалось загрузить кассы');setAccounts(data.accounts);}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки');}finally{setLoading(false);}}
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('cash-refresh',refresh);return()=>window.removeEventListener('cash-refresh',refresh);},[]);
 useEffect(()=>{if(!selected)return;let active=true;setOperations([]);setCourierOrders([]);setHistoryError('');setHistoryLoading(true);fetch('/api/cash?employeeId='+encodeURIComponent(selected.id),{cache:'no-store'}).then(async r=>{const data=await r.json() as {operations:Operation[];courierOrders?:Order[];error?:string};if(!r.ok)throw Error(data.error||'Не удалось загрузить историю');if(active){setOperations(data.operations);setCourierOrders(data.courierOrders||[]);}}).catch(e=>{if(active)setHistoryError(e.message);}).finally(()=>{if(active)setHistoryLoading(false);});return()=>{active=false;};},[selected]);
 return <section className="stack"><div className="toolbar"><div><h2>Кассы сотрудников</h2><p className="muted">Нажмите на карточку, чтобы посмотреть поступления и списания.</p></div><button className="secondary" disabled={loading} onClick={()=>void load()}>Обновить кассы</button></div>{error&&<p role="alert" className="notice amber">{error}</p>}{loading&&!accounts.length&&<p>Загрузка касс…</p>}<div className="employee-cash-grid">{accounts.map(a=><button className="employee-cash-card" key={a.id} onClick={()=>setSelected(a)}><span className="employee-cash-role">{roles[a.role]}</span><h3>{a.name}</h3><small>{a.login}</small><dl><div><dt>{a.role==='courier'?'Деньги на руках':'В кассе'}</dt><dd>{money(a.balance/100)}</dd></div><div><dt>{a.role==='courier'?'Посылки ожидают приёма':'Ожидает поступления'}</dt><dd>{money(a.pending/100)}</dd></div>{a.role==='courier'&&<><div><dt>Заказы на руках</dt><dd>{money((a.parcels||0)/100)}</dd></div><div><dt>Под отчётом</dt><dd>{money((a.accountable||0)/100)}</dd></div></>}</dl><span className="employee-cash-open">История поступлений и списаний →</span></button>)}</div>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="client-detail-dialog"><DialogHeader><DialogTitle>Касса · {selected?.name}</DialogTitle><DialogDescription>{selected?.role==='courier'?'Учёт посылок и денег по каждому заказу. Ожидающие приёма посылки не входят в сумму под отчётом.':'Поступления и списания. Ожидающие переводы выделены серым и ещё не входят в баланс.'}</DialogDescription></DialogHeader><div className="sheet-body stack">{historyLoading?<p>Загрузка истории…</p>:historyError?<p role="alert" className="notice amber">{historyError}</p>:selected?.role==='courier'?<>{courierOrders.map(o=><section className="notice stack" key={o.id}><h3>{o.id} · {money(o.courier!.amount)}</h3><p>Передан логистом: {stamp(o.courier!.assignedAt)}</p><p>{o.courier!.acceptedAt?`Принято курьером: ${stamp(o.courier!.acceptedAt)} · заказы +${money(o.courier!.amount)}`:'Ожидает приёма курьером'}</p>{o.redeemedAt&&<p>Клиент оплатил: {stamp(o.redeemedAt)} · заказы −{money(o.courier!.amount)}, деньги +{money(o.courier!.amount)}</p>}{o.returnedAt&&<p>Возврат: {stamp(o.returnedAt)} · {o.reason||'Ожидает возврата на склад'}</p>}{o.warehouseReturnedAt&&<p>Возврат принят на склад: {stamp(o.warehouseReturnedAt)} · заказы −{money(o.courier!.amount)}</p>}{o.paymentReceivedAt&&<p>Логист принял оплату: {stamp(o.paymentReceivedAt)} · деньги −{money(o.courier!.amount)}</p>}</section>)}{!courierOrders.length&&<p>Курьеру пока не передавали заказы.</p>}</>:<><Table><TableHeader><TableRow><TableHead>Дата</TableHead><TableHead>Назначение</TableHead><TableHead>От кого / кому</TableHead><TableHead>Сумма</TableHead><TableHead>Состояние</TableHead></TableRow></TableHeader><TableBody>{operations.map(o=>{const incoming=o.recipient===selected?.id;const pending=o.kind==='transfer'&&!o.accepted_at;return <TableRow key={o.id} style={pending?{background:'#eef0f3',color:'#697586'}:undefined}><TableCell>{o.date.split('-').reverse().join('.')}<small className="block muted">Записано: {stamp(o.created_at)}</small></TableCell><TableCell>{o.purpose}</TableCell><TableCell>{incoming?o.sender_name||'Пополнение':o.recipient_name||'Выдача из кассы'}</TableCell><TableCell>{incoming?'+':'−'}{money(o.amount/100)}</TableCell><TableCell>{pending?incoming?'Ожидает получения':'Передано · ожидает подтверждения':o.kind==='spend'?'Списано':incoming?'Зачислено':'Получатель подтвердил'}{o.accepted_at&&<small className="block muted">{stamp(o.accepted_at)}</small>}</TableCell></TableRow>;})}</TableBody></Table>{!operations.length&&<p className="muted">У сотрудника пока нет операций по кассе.</p>}</>}</div></DialogContent></Dialog>
 </section>;
}
