'use client';
import {useEffect,useState} from 'react';
import {Switch} from '@/components/ui/switch';
type Product={id:string;name:string;lv_id?:string;lv_name?:string;available?:number};
type Operation={id:string;name:string;quantity:number;state:string;at:string;error?:string;comment:string};
type View={configured:boolean;host:string;enabled:boolean;trackCrm:boolean;links:Record<string,string>;health?:{at:string;active?:number;sent?:number;unknown?:number;error?:string};products:Product[];operations:Operation[]};
export function LvWarehouseSettings({actorId}:{actorId:string}){
 const [view,setView]=useState<View|null>(null),[host,setHost]=useState(''),[token,setToken]=useState(''),[enabled,setEnabled]=useState(false),[trackCrm,setTrack]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [goods,setGoods]=useState<{id:string;name:string;available:number}[]>([]),[links,setLinks]=useState<Record<string,string>>({}),[confirm,setConfirm]=useState<{id?:string;applied?:boolean;remove?:boolean}|null>(null);
 const accept=(v:View)=>{setView(v);setHost(v.host);setEnabled(v.enabled);setTrack(v.trackCrm);setLinks(v.links);};
 useEffect(()=>{fetch('/api/lv-warehouse?actorId='+encodeURIComponent(actorId)).then(async r=>{const d=await r.json() as View & {error?:string;goods:{id:string;name:string;available:number}[]};if(!r.ok)throw Error(d.error);accept(d);}).catch(e=>setMessage(e.message));},[actorId]);
 async function action(action:string,extra:Record<string,unknown>={}){
  setBusy(true);setMessage('');try{
   const r=await fetch('/api/lv-warehouse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actorId,action,host,token,enabled,trackCrm,links,...extra})});const d=await r.json() as View & {error?:string;goods:{id:string;name:string;available:number}[]};if(!r.ok)throw Error(d.error);
   if(action==='preview'){setGoods(d.goods);setMessage('Активных товаров в ЛВ: '+d.goods.length+'. Проверьте соответствия перед сохранением.');}
   else{accept(d);setToken('');setConfirm(null);setMessage(action==='sync'?'Обмен завершён.':action==='delete'?'Подключение удалено. Товары, остатки и история сохранены.':'Сохранено.');}
  }catch(e){setMessage(e instanceof Error?e.message:'Не удалось выполнить действие');}finally{setBusy(false);}
 }
 return <section className="stack"><p>Активные товары и актуальные остатки поступают из ЛВ. Обмен выполняется каждую минуту, даже при закрытой CRM.</p>
 <fieldset className="stack order-fields" disabled={busy||!view}><div className="form-grid"><label className="field"><span>Адрес проекта ЛВ</span><input value={host} onChange={e=>setHost(e.target.value)} placeholder="project.leadvertex.ru" autoComplete="off"/></label><label className="field"><span>Ключ API администратора</span><input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder={view?.configured?'Сохранён; оставьте пустым, чтобы не менять':'Введите ключ'}/></label></div>
 <label className="packing-ready" htmlFor="lv-enabled"><Switch id="lv-enabled" checked={enabled} onCheckedChange={setEnabled} disabled={busy||!view}/>Обмен с ЛВ включён</label>
 <label className="packing-ready" htmlFor="lv-track-crm"><Switch id="lv-track-crm" checked={trackCrm} onCheckedChange={setTrack} disabled={busy||!view}/>Учитывать остатки нашей CRM</label>
 <p className="muted">{trackCrm?'CRM передаёт в ЛВ новые резервы, снятие резервов, принятые возвраты и ручные движения склада. Выкуп уже зарезервированного товара не списывает его повторно.':'Изменения нашей CRM не отправляются в ЛВ. Локальные резервы продолжают учитываться в доступном количестве CRM.'} Выключение не отменяет уже переданные движения. При повторном включении передаётся накопившаяся разница.</p>
 <small className="muted">Переключатели применяются после нажатия «Проверить и сохранить».</small><div className="order-actions"><button className="secondary" type="button" onClick={()=>action('preview')}>Проверить товары ЛВ</button><button className="primary" type="button" onClick={()=>action('save')}>Проверить и сохранить</button></div>
 {goods.length>0&&<details open><summary>Соответствие товаров · {goods.length}</summary><p className="muted">Одинаковые названия сопоставятся автоматически. Если названия отличаются, выберите существующую карточку. Иначе будет добавлен новый товар. Данные СДЭК существующих карточек сохраняются.</p>{goods.map(g=><label className="field" key={g.id}><span>{g.name} · ЛВ {g.id} · {g.available} шт.</span><select value={links[g.id]||''} disabled={view?.products.some(p=>p.lv_id===g.id)} onChange={e=>setLinks(old=>{const next={...old};if(e.target.value)next[g.id]=e.target.value;else delete next[g.id];return next;})}><option value="">По названию / создать новый</option>{view?.products.filter(p=>!p.lv_id||p.lv_id===g.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>)}</details>}
 </fieldset>
 {view?.configured&&<div className="notice" style={{display:'block'}}><b>{view.enabled?'Обмен включён':'Обмен отключён'}</b><p>{view.health?.at?'Последняя проверка: '+new Date(view.health.at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})+' МСК':'Первая синхронизация ещё не выполнена.'}</p><p>Связано товаров: {view.products.filter(p=>p.lv_id).length}. {view.health?.error||''}</p>{view.enabled&&<button className="secondary" disabled={busy} onClick={()=>action('sync')}>{busy?'Обмен…':'Обновить сейчас'}</button>}</div>}
 <p role="status">{message}</p>
 {!!view?.operations.length&&<details open={view.operations.some(o=>o.state==='unknown')}><summary>История обмена остатками</summary>{view.operations.map(o=><div className="item-read" key={o.id} style={{display:'block'}}><b>{o.name} · {o.quantity>0?'+':''}{o.quantity} шт.</b><small>{new Date(o.at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})} · {({applied:'Подтверждено',unknown:'Требуется сверка',sending:'Отправляется',not_applied:'Не выполнено — разрешён повтор'} as Record<string,string>)[o.state]}</small><small>{o.comment}</small>{o.state==='unknown'&&<><p className="orange">{o.error}</p><p>Найдите номер операции в ЛВ → Склад → История изменения остатков.</p><button className="secondary" disabled={busy} onClick={()=>setConfirm({id:o.id,applied:true})}>В истории ЛВ выполнено</button> <button className="secondary" disabled={busy} onClick={()=>setConfirm({id:o.id,applied:false})}>В истории ЛВ не выполнено</button></>}</div>)}</details>}
 <div className="notice" style={{display:'block'}}><b>Напоминание о переходе с ЛВ</b><p>Когда полностью перейдём в нашу CRM: сначала отключить обмен с ЛВ, проверить незавершённые операции, затем удалить подключение. Товары и учёт склада нашей CRM продолжают работать.</p></div>
 {view?.configured&&!view.enabled&&<button className="secondary" disabled={busy} onClick={()=>setConfirm({remove:true})}>Удалить подключение ЛВ</button>}
 {confirm&&<div className="notice" style={{display:'block'}}><p>{confirm.remove?'Удалить сохранённый ключ и подключение ЛВ? Товары и история останутся.':confirm.applied?'Вы проверили историю ЛВ и убедились, что эта операция выполнена? Повторно она отправляться не будет.':'Вы проверили историю ЛВ и убедились, что операция НЕ выполнена? При следующем обмене CRM сможет повторить движение.'}</p><button className="primary" disabled={busy} onClick={()=>action(confirm.remove?'delete':'resolve',{...confirm,confirmed:true})}>Подтверждаю</button> <button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Назад</button></div>}
 </section>;
}
