'use client';
import {useEffect,useState} from 'react';
type Template={id:string;name:string;text:string};
async function post(body:unknown){const r=await fetch('/api/mainsms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as any;if(!r.ok)throw Error(d.error||d.message||'Ошибка MainSMS');return d;}
export function MainSmsSettings({actorId}:{actorId:string}){
 const [config,setConfig]=useState({project:'',sender:'',apiKey:'',templates:[] as Template[]}),[revision,setRevision]=useState(''),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/mainsms?'+new URLSearchParams({actorId})).then(async r=>{const d=await r.json() as any;if(!r.ok)throw Error(d.error);setConfig({project:d.project||'',sender:d.sender||'',apiKey:'',templates:d.templates});setRevision(d.revision);setConfigured(d.configured);}).catch(e=>setMessage(e.message)).finally(()=>setBusy(false));},[actorId]);
 async function action(kind:string){setBusy(true);setMessage('');try{const d=await post({action:kind,actorId,config,revision});if(d.revision){setRevision(d.revision);setConfigured(true);setConfig(c=>({...c,apiKey:''}));}setMessage(d.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="stack"><p>SMS клиенту из карточки заказа. Укажите проект и API-ключ из кабинета MainSMS. Используйте согласованное имя отправителя или оставьте его пустым.</p><fieldset disabled={busy} className="stack order-fields"><div className="form-grid">{(['project','sender','apiKey'] as const).map((key,i)=><label className="field" key={key}><span>{['Проект','Имя отправителя','API-ключ'][i]}</span><input type={key==='apiKey'?'password':'text'} autoComplete="off" value={config[key]} placeholder={key==='apiKey'&&configured?'Сохранён — оставьте пустым, чтобы не менять':''} onChange={e=>setConfig({...config,[key]:e.target.value})}/></label>)}</div><h3>Шаблоны SMS</h3><p className="muted">{'{client} — имя клиента, {order} — номер заказа. Эти шаблоны хранятся в CRM.'}</p>{config.templates.map((t,i)=><section className="settings-card" style={{padding:16}} key={t.id}><label className="field"><span>Название шаблона</span><input value={t.name} onChange={e=>setConfig({...config,templates:config.templates.map((x,n)=>n===i?{...x,name:e.target.value}:x)})}/></label><label className="field"><span>Текст SMS</span><textarea rows={3} maxLength={1000} value={t.text} onChange={e=>setConfig({...config,templates:config.templates.map((x,n)=>n===i?{...x,text:e.target.value}:x)})}/></label><button type="button" className="text-button" onClick={()=>setConfig({...config,templates:config.templates.filter(x=>x.id!==t.id)})}>Убрать шаблон</button></section>)}<button className="secondary" onClick={()=>setConfig({...config,templates:[...config.templates,{id:crypto.randomUUID(),name:'',text:''}]})}>Добавить шаблон</button><div className="action-buttons"><button className="primary" onClick={()=>action('save')}>Сохранить настройки и шаблоны</button><button className="secondary" disabled={!configured} onClick={()=>action('check')}>Проверить подключение</button></div></fieldset><p role="status">{busy?'Загрузка…':message}</p></div>;
}
export function OrderSms({actorId,orderId,testOnly}:{actorId:string;orderId:string;testOnly?:boolean}){
 const [templates,setTemplates]=useState<Template[]>([]),[selected,setSelected]=useState(''),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[configured,setConfigured]=useState(false);
 useEffect(()=>{fetch('/api/mainsms?'+new URLSearchParams({actorId})).then(async r=>{const d=await r.json() as any;if(!r.ok)throw Error(d.error);setTemplates(d.templates);setConfigured(d.configured);}).catch(e=>setMessage(e.message));},[actorId]);
 async function action(kind:'preview'|'send'){setBusy(true);setMessage('');try{const d=await post({action:kind,actorId,orderId,templateId:selected,token:preview?.token});if(kind==='preview')setPreview(d);else{setPreview(null);setMessage(d.message);window.dispatchEvent(new Event('crm-refresh'));}}catch(e){setMessage((e as Error).message);if(kind==='send')setPreview(null);}finally{setBusy(false);}}
 return <section className="stack"><h3>SMS клиенту</h3>{testOnly?<p>Отправка SMS тестовым клиентам отключена.</p>:!configured?<p>Администратору нужно подключить MainSMS в настройках интеграций.</p>:<><label className="field"><span>Готовое сообщение</span><select disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setPreview(null);}}><option value="">Выберите шаблон</option>{templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label>{!templates.length&&<p>Добавьте шаблоны в настройках MainSMS.</p>}<button className="secondary" disabled={busy||!selected} onClick={()=>action('preview')}>Предпросмотр SMS</button>{preview&&<div className="stack notice" style={{display:'grid'}}><b>{preview.recipient}</b><span>Отправитель: {preview.sender}</span><p style={{whiteSpace:'pre-wrap'}}>{preview.text}</p><small>Отправка платная, по тарифу MainSMS. Нажатие отправит это сообщение клиенту.</small><button className="primary" disabled={busy} onClick={()=>action('send')}>Отправить SMS</button></div>}</>}<p role="status">{busy?'Обработка…':message}</p></section>;
}
