"use client";
import {useState} from 'react';
import {BarChart3,ChevronDown} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from './ui/dropdown-menu';
import {operatorStats} from '../lib/operator-stats';
import {money,statuses,type Order,type State,type Employee} from '../lib/crm';
export function OperatorStats({state,actor,onOpenOrder}:{state:State;actor:Employee;onOpenOrder:(id:string)=>void}){
 const [open,setOpen]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState('');
 if(!['admin','department_head','operator'].includes(actor.role))return null;
 const invalid=!!from&&!!to&&from>to,rows=invalid?[]:operatorStats(state,actor,from,to);
 function openOrder(id:string){setOpen(false);onOpenOrder(id);}
 function metric(value:string|number,orders:Order[],label:string){
  if(!orders.length)return value;
  if(orders.length===1)return <button className="table-link" aria-label={`${label}: открыть заказ ${orders[0].id}`} onClick={()=>openOrder(orders[0].id)}>{value}</button>;
  return <DropdownMenu><DropdownMenuTrigger asChild><button className="table-link" aria-label={`${label}: выбрать заказ`}>{value} <ChevronDown size={13} style={{display:'inline'}}/></button></DropdownMenuTrigger><DropdownMenuContent style={{maxHeight:320,maxWidth:'min(480px,90vw)',zIndex:100}}>{orders.map(o=><DropdownMenuItem key={o.id} onSelect={()=>openOrder(o.id)}><span><b>{o.id}</b> · {state.clients.find(c=>c.id===o.clientId)?.name||'Клиент'}<br/><small>{statuses[o.status]} · {money(o.items.reduce((n,i)=>n+i.price*i.quantity,0))}</small></span></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>;
 }
 const allOrders=(key:'created'|'newOrders'|'reviewed'|'cancelled')=>rows.flatMap(r=>r.orderLists[key]);
 const count=rows.reduce((n,r)=>n+r.reviewed,0),amount=rows.reduce((n,r)=>n+Math.round(r.amount*100),0)/100;
 return <><button className="secondary" onClick={()=>{const today=new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Moscow"});setFrom(today);setTo(today);setOpen(true);}} title="Статистика операторов"><BarChart3 size={18}/>Статистика</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="form-dialog operator-stats-dialog"><DialogHeader><DialogTitle>Статистика операторов</DialogTitle><DialogDescription>Период по дате создания заказа, время Москвы. Показатели отражают текущее состояние заказов.</DialogDescription></DialogHeader><div className="stack"><div className="action-buttons"><label>С даты<input aria-label="Начало периода" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По дату<input aria-label="Конец периода" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary" onClick={()=>{setFrom('');setTo('');}}>За всё время</button></div>{invalid?<p role="alert">Начало периода не может быть позже конца.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>Логин оператора</th><th>Создано заказов</th><th>В статусе «Новый»</th><th>После проверки администратора</th><th>Отменён</th><th>Сумма заказов</th><th>Средний чек</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.login}</td><td>{metric(r.created,r.orderLists.created,r.login||"Оператор")}</td><td>{metric(r.newOrders,r.orderLists.newOrders,r.login||"Оператор")}</td><td>{metric(r.reviewed,r.orderLists.reviewed,r.login||"Оператор")}</td><td>{metric(r.cancelled,r.orderLists.cancelled,r.login||"Оператор")}</td><td>{metric(money(r.amount),r.orderLists.reviewed,"Сумма заказов")}</td><td>{metric(money(r.average),r.orderLists.reviewed,"Средний чек")}</td></tr>)}</tbody><tfoot><tr><th>Итого</th><td>{metric(rows.reduce((n,r)=>n+r.created,0),allOrders("created"),"Итого")}</td><td>{metric(rows.reduce((n,r)=>n+r.newOrders,0),allOrders("newOrders"),"Итого")}</td><td>{metric(count,allOrders("reviewed"),"После проверки")}</td><td>{metric(rows.reduce((n,r)=>n+r.cancelled,0),allOrders("cancelled"),"Итого")}</td><td>{metric(money(amount),allOrders("reviewed"),"Сумма заказов")}</td><td>{metric(money(count?amount/count:0),allOrders("reviewed"),"Средний чек")}</td></tr></tfoot></table>{!rows.length&&<p>Нет операторов для отображения.</p>}</div>}<p className="muted">«Новый»: оформление, подтверждение и возврат оператору. После проверки учитываются заказы, направленные администратором на упаковку или дополнительное подтверждение. Исключаются только отменённые заказы. Недозвон, перезвон и возврат оператору сохраняют заказ в этом показателе.</p></div></DialogContent></Dialog></>;
}
