"use client";
import {useState} from 'react';
import {BarChart3} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {operatorStats} from '../lib/operator-stats';
import {money,type State,type Employee} from '../lib/crm';
export function OperatorStats({state,actor}:{state:State;actor:Employee}){
 const [open,setOpen]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState('');
 if(!['admin','department_head','operator'].includes(actor.role))return null;
 const invalid=!!from&&!!to&&from>to,rows=invalid?[]:operatorStats(state,actor,from,to);
 const count=rows.reduce((n,r)=>n+r.reviewed,0),amount=rows.reduce((n,r)=>n+Math.round(r.amount*100),0)/100;
 return <><button className="secondary" onClick={()=>{const today=new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Moscow"});setFrom(today);setTo(today);setOpen(true);}} title="Статистика операторов"><BarChart3 size={18}/>Статистика</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="form-dialog operator-stats-dialog"><DialogHeader><DialogTitle>Статистика операторов</DialogTitle><DialogDescription>Период по дате создания заказа, время Москвы. Показатели отражают текущее состояние заказов.</DialogDescription></DialogHeader><div className="stack"><div className="action-buttons"><label>С даты<input aria-label="Начало периода" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По дату<input aria-label="Конец периода" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary" onClick={()=>{setFrom('');setTo('');}}>За всё время</button></div>{invalid?<p role="alert">Начало периода не может быть позже конца.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>Логин оператора</th><th>Создано заказов</th><th>В статусе «Новый»</th><th>После проверки администратора</th><th>Отменён</th><th>Сумма заказов</th><th>Средний чек</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.login}</td><td>{r.created}</td><td>{r.newOrders}</td><td>{r.reviewed}</td><td>{r.cancelled}</td><td>{money(r.amount)}</td><td>{money(r.average)}</td></tr>)}</tbody><tfoot><tr><th>Итого</th><td>{rows.reduce((n,r)=>n+r.created,0)}</td><td>{rows.reduce((n,r)=>n+r.newOrders,0)}</td><td>{count}</td><td>{rows.reduce((n,r)=>n+r.cancelled,0)}</td><td>{money(amount)}</td><td>{money(count?amount/count:0)}</td></tr></tfoot></table>{!rows.length&&<p>Нет операторов для отображения.</p>}</div>}<p className="muted">«Новый»: оформление, подтверждение и возврат оператору. После проверки учитываются заказы, направленные администратором на упаковку или дополнительное подтверждение. Исключаются только отменённые заказы. Недозвон, перезвон и возврат оператору сохраняют заказ в этом показателе.</p></div></DialogContent></Dialog></>;
}
