import {previousThreeMonths,repeatSales,moscowDate} from '@/lib/base-distribution';
import {initBaseDispatch,queueBaseDispatch} from '@/lib/base-dispatch';
import {importBase} from '@/lib/base-import-store';
import {authenticated} from '@/lib/api-auth';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db} from '@/lib/db';
import {baseSettingsSchema,initialBaseSettings,normalizeBaseSheet,type BaseSettings} from '@/lib/base-policy';
import {clientAssignment,clientSheet,type Client,type Employee} from '@/lib/crm';
import {z} from 'zod';
async function admin(req:Request){if(!await getChatGPTUser())return false;const id=new URL(req.url).searchParams.get('actorId')||'';const row=await db().prepare('SELECT data FROM employees WHERE id=?').bind(id).first<{data:string}>();return !!row&&JSON.parse(row.data).role==='admin';}
// Aggregate in SQLite; this response never includes client cards or phone numbers.
async function counts(){return (await db().prepare(`SELECT CASE WHEN json_extract(data,'$.baseType')='J' THEN 'J' ELSE 'M' END AS base,COALESCE(json_extract(data,'$.sheet'),'') AS sheet,COALESCE(json_extract(data,'$.source'),'') AS source,COUNT(*) AS total,SUM(CASE WHEN COALESCE(json_extract(data,'$.owner'),'')<>'' THEN 1 ELSE 0 END) AS assigned FROM clients GROUP BY base,sheet,CASE WHEN json_extract(data,'$.sheet') IS NULL THEN source ELSE '' END`).all<{base:'M'|'J';sheet:string;source:string;total:number;assigned:number}>()).results;}
async function read(){const row=await db().prepare("SELECT data FROM settings WHERE id='base-settings'").first<{data:string}>();if(!row)return {config:initialBaseSettings(),revision:''};const saved=JSON.parse(row.data);return {config:baseSettingsSchema.parse(saved.config),revision:String(saved.revision||'')};}
export const GET=authenticated(async req=>{if(!await admin(req))return Response.json({error:'Раздел доступен администратору'},{status:403});await initBaseDispatch(db());const saved=await read(),raw=await counts();const summary:Record<string,Record<string,{total:number;assigned:number}>>={M:{},J:{}};for(const row of raw){const name=normalizeBaseSheet(row.sheet||row.source.match(/\.xlsx · (.+)$/i)?.[1]||'');const old=summary[row.base][name]||{total:0,assigned:0};summary[row.base][name]={total:old.total+row.total,assigned:old.assigned+row.assigned};if(!saved.config[row.base].sheets.some(s=>s.name===name))saved.config[row.base].sheets.push({name,automatic:false,projectId:'',cycleDays:20,sendTime:'21:00'});}const operators=(await db().prepare("SELECT data FROM employees WHERE json_extract(data,'$.role')='operator'").all<{data:string}>()).results.map(r=>{const e=JSON.parse(r.data);return {id:e.id,name:e.name,login:e.login,baseAccess:e.baseAccess||'both'};});const issues=(await db().prepare("SELECT i.job_id,i.client_id,i.state,i.error,json_extract(c.data,'$.name') AS name,json_extract(c.data,'$.phone') AS phone FROM base_dispatch_items i JOIN clients c ON c.id=i.client_id WHERE i.state IN ('unknown','failed') ORDER BY i.updated_at DESC LIMIT 100").all()).results;const dispatches=(await db().prepare("SELECT j.*,COUNT(i.client_id) AS total,SUM(i.state='sent') AS sent,SUM(i.state='unknown') AS uncertain,SUM(i.state='failed') AS failed,SUM(i.state IN ('pending','sending')) AS pending FROM base_dispatch_jobs j LEFT JOIN base_dispatch_items i ON i.job_id=j.id GROUP BY j.id ORDER BY j.created_at DESC LIMIT 20").all()).results;const paid=(await db().prepare("SELECT data FROM orders WHERE json_extract(data,'$.status')='redeemed'").all<{data:string}>()).results.map(r=>JSON.parse(r.data));const period=saved.config.retention.from&&saved.config.retention.to?saved.config.retention:previousThreeMonths();const stats=repeatSales(paid,period.from,period.to);return Response.json({...saved,summary,operators,dispatches,stats,issues,health:JSON.parse((await db().prepare("SELECT data FROM settings WHERE id='base-health'").first<{data:string}>())?.data||'null'),releasedToday:(await db().prepare("SELECT COALESCE(json_extract(data,'$.baseType'),'M') AS base,COUNT(*) AS total FROM clients WHERE COALESCE(json_extract(data,'$.owner'),'')='' AND date(json_extract(data,'$.releasedAt'),'+3 hours')=? GROUP BY base").bind(moscowDate()).all()).results});});
export const POST=authenticated(async req=>{if(!await admin(req))return Response.json({error:'Настройки доступны администратору'},{status:403});try{const input=await req.json() as any;
 if(input.action==='resolveDispatch'){
 const p=z.object({job:z.string().max(100),client:z.string().max(100),outcome:z.enum(['sent','not_sent'])}).parse(input);await initBaseDispatch(db());const item=await db().prepare("SELECT i.*,j.distribution_date FROM base_dispatch_items i JOIN base_dispatch_jobs j ON j.id=i.job_id WHERE i.job_id=? AND i.client_id=? AND i.state IN ('unknown','failed')").bind(p.job,p.client).first<{state:string;distribution_date:string}>();if(!item)throw Error('Запись уже обработана');const at=new Date().toISOString();await db().batch([...(p.outcome==='sent'?[db().prepare("UPDATE clients SET data=json_set(data,'$.distributedAt',?),version=version+1 WHERE id=? AND EXISTS(SELECT 1 FROM base_dispatch_items WHERE job_id=? AND client_id=? AND state IN ('unknown','failed'))").bind(item.distribution_date,p.client,p.job,p.client)]:[]),db().prepare("UPDATE base_dispatch_items SET state=?,error='',updated_at=? WHERE job_id=? AND client_id=? AND state IN ('unknown','failed')").bind(p.outcome==='sent'?'sent':'cancelled',at,p.job,p.client)]);return Response.json({ok:true});
 }
 if(input.action==='dispatch'){const p=z.object({base:z.enum(['M','J']),sheet:z.string().max(60),project:z.string().regex(/^\d+$/),count:z.number().int().min(1).max(100000)}).parse(input);return Response.json(await queueBaseDispatch(db(),p));}
 if(input.action==='import')return Response.json(await importBase(input,new URL(req.url).searchParams.get('actorId')||''));
 if(input.action==='assign'){
 const p=z.object({base:z.enum(['M','J']),sheet:z.string().min(1).max(60),operator:z.string().min(1).max(100),count:z.number().int().min(1).max(1000),freshOnly:z.boolean().default(false)}).parse(input);
 if(['К','ЧС','ПВ'].includes(p.sheet))throw Error('Этот лист не участвует в раздаче');
 const employee=await db().prepare("SELECT data FROM employees WHERE id=?").bind(p.operator).first<{data:string}>();const operator:Employee=employee?JSON.parse(employee.data):null;
 if(!operator||operator.role!=='operator'||operator.baseAccess&&operator.baseAccess!=='both'&&operator.baseAccess!==p.base)throw Error('Оператор не обрабатывает выбранную базу');
 await initBaseDispatch(db());const settings=await read();if(!settings.config[p.base].sheets.some(x=>x.name===p.sheet))throw Error('Сначала сохраните настройки листа');
 const rows=(await db().prepare(`SELECT id,data,version FROM clients WHERE COALESCE(json_extract(data,'$.baseType'),'M')=? AND COALESCE(json_extract(data,'$.owner'),'')='' AND COALESCE(json_extract(data,'$.sheet'),'')=? AND (?=0 OR date(json_extract(data,'$.releasedAt'),'+3 hours')=?) AND NOT EXISTS(SELECT 1 FROM base_dispatch_items WHERE client_id=clients.id AND state IN ('pending','sending','unknown')) ORDER BY COALESCE(json_extract(data,'$.distributedAt'),''),id LIMIT ?`).bind(p.base,p.sheet,p.freshOnly?1:0,moscowDate(),p.count).all<{id:string;data:string;version:number}>()).results;
 const at=new Date().toISOString(),marker=crypto.randomUUID();const sql=rows.flatMap(row=>{const c:Client={...JSON.parse(row.data),version:row.version};const next={...c,...clientAssignment(c,p.operator,at,p.sheet),_baseAssign:marker};const event={id:'EV-'+crypto.randomUUID(),clientId:c.id,orderId:'',actorId:new URL(req.url).searchParams.get('actorId'),actor:'Администратор',at,text:'Ручная раздача из базы '+p.base+' · '+clientSheet(c)+' → '+operator.login};return [db().prepare("UPDATE clients SET data=?,version=version+1 WHERE id=? AND version=? AND COALESCE(json_extract(data,'$.owner'),'')=''").bind(JSON.stringify(next),row.id,row.version),db().prepare("INSERT INTO events(id,client_id,order_id,at,data) SELECT ?,?,'',?,? WHERE EXISTS(SELECT 1 FROM clients WHERE id=? AND json_extract(data,'$._baseAssign')=?)").bind(event.id,c.id,at,JSON.stringify(event),c.id,marker)];});
 const results=sql.length?await db().batch(sql):[];return Response.json({assigned:results.filter((_,i)=>i%2===0).reduce((n,r)=>n+(r.meta.changes||0),0)});
 }
 const p=z.object({revision:z.string().max(100),config:baseSettingsSchema}).parse(input);const old=await read();if(old.revision!==p.revision)return Response.json({error:'Настройки изменились. Обновите страницу.'},{status:409});const existing=await counts();for(const row of existing){const name=normalizeBaseSheet(row.sheet||row.source.match(/\.xlsx · (.+)$/i)?.[1]||'');if(!p.config[row.base].sheets.some(s=>s.name===name))throw Error('Нельзя удалить или переименовать лист с клиентами: '+name);}
 const next={config:p.config,revision:crypto.randomUUID()};const result=await db().prepare("INSERT INTO settings(id,data) VALUES('base-settings',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE COALESCE(json_extract(settings.data,'$.revision'),'')=?").bind(JSON.stringify(next),p.revision).run();if(!result.meta.changes)return Response.json({error:'Настройки изменились. Обновите страницу.'},{status:409});return Response.json(next);
 }catch(e){return Response.json({error:e instanceof z.ZodError?e.issues[0]?.message:e instanceof Error?e.message:'Не удалось сохранить'},{status:400});}});
